### PR TITLE
Added operation mode to the camera attributes (needed for FireWire cameras)

### PR DESCRIPTION
**Pull request by Nurgak**
`camera_firewire` can function in [mode B](https://en.wikipedia.org/wiki/IEEE_1394#FireWire_800_.28IEEE_1394b-2002.29) where the bus speed can be increased to 800Mbit/s, the legacy mode only allows a maximum FireWire bus speed of 400. This new attribute in the `camera_interface` allows the `camera_firewire` (once the changes are accepted there as well) to function with mode B.

In either case accepting this pull for `camera_interface` will not break anything as it is just an additional attribute, but this pull is required for the `camera_firewire` to work properly with mode B as it depends on `camera_interface`.

### CODE REVIEW

**Comment by doudou** [comment]
IMO this should not leak into the camera_interface generic attributes. Wouldn't making it a property on the camera_firewire orogen task be enough ?

**Comment by Nurgak** [comment]
The `camera_firewire` library and orogen need to be modified as well of course, but `camera_interface` needs an additional attribute, it is a legitimate (IMO currently missing) property ([dc1394operation_mode_t](http://libdc1394-22.sourcearchive.com/documentation/2.1.3-4/video_8h_source.html)), so I think it makes sense to add it to `camera_interface` just like all the other attributes.

Also making a specific property somewhere else would break the [`CamFireWire::setAttrib`](https://github.com/rock-drivers/drivers-camera_firewire/blob/master/src/CamFireWire.cpp#L751) method consistency. This is the reason I opted to do it this way.

**Comment by doudou** [comment]
@D-Alex : opinion ?

@Nurgak : is that something you would actually change dynamically ? The `set*` calls are really designed for this

**Comment by Nurgak** [comment]
I do set it in the camera settings [here](https://github.com/hdpr-rover/bundles-hdpr/blob/master/config/orogen/camera_firewire::CameraTask.yml#L184) during configuration setup, without it the [`isochronous_speed`](https://github.com/hdpr-rover/bundles-hdpr/blob/master/config/orogen/camera_firewire::CameraTask.yml#L174) of 800 would not be possible. The 800 speed lowers used bandwidth by half and we were constrained by it until we figured out the 800 setting.

Another possibility would be to separate all attributes related to firewire cameras somewhere else...

**Comment by D-Alex** [comment]
In principle I do agree that the camera interface should reflect the different attributes and modes of the cameras derived from it. However, the operation mode seems to be very specific to firewire cameras. Therefore, how about using the int attribute 'StreamBytesPerSecond' to encode the different modes? 

The naming is maybe not perfect but the reason for this is that the camera interface was mainly designed for GigE cameras.

**Comment by pagnamen** [comment]
Regarding the previous pull request, I agree specific firewire attributes should be limited to the firewire components.
On the other hand, there were already firewire specific attributes in this header (none in camera firewire) so we did not want to have them all over the place. This can be changed in the future, but needs to be consistent. For example, there are a lot of ethernet/IP specific attributes in here.

We have new commits for the following reasons:

1) Applying modes before values so that the values are properly configured in the first run if a mode is changed from auto to manual
2) Changing the name of the SHUTTER functionality (which was wrongly called exposure). Now EXPOSURE manages the exposure and SHUTTER the shutter.
3) (Together with the previous 2 reasons) Being able to change mode, value and power (functionality on/off) for the following DC1394 features: exposure, gain, shutter, saturation, sharpness, gamma, white balance.

This pull request depends on the following pull requests:
a) camera_firewire (library)
b) camera_base (orogen)

**Comment by m0rsch1** [comment]
Dear Maintainers,

we are looking forward to get these pull requests merged, so we can use the master branch again.
Do we have to do anything else? What are the obstacles to merge the pull requests?

BR,

Moritz@ESA

> The naming is maybe not perfect but the reason for this is that the camera interface was mainly designed for GigE cameras.

I agree. So a new attribute with a better name seems more suitable for others (possibly ROCK newcomers)

**Pull request merged**
